/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef query_engin_G2_CONSTANTS_H
#define query_engin_G2_CONSTANTS_H

#include "query_engin_G2_types.h"



class query_engin_G2Constants {
 public:
  query_engin_G2Constants();

};

extern const query_engin_G2Constants g_query_engin_G2_constants;



#endif
