/*
 * RedisProxyServiceHandler.h
 *
 *  Created on: May 10, 2016
 *      Author: liang
 */

#ifndef REDISPROXYSERVICEHANDLER_H_
#define REDISPROXYSERVICEHANDLER_H_

// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "RedisProxy.h"
#include "RedisProxyService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

#include <iostream>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class RedisProxyServiceHandler: virtual public RedisProxyServiceIf {
public:
	RedisProxyServiceHandler();

	void process(Response& response, const Request& request);

private:
	shared_ptr<RedisProxy> redisProxy;
};

#endif /* REDISPROXYSERVICEHANDLER_H_ */
