/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "query_engin_G2_constants.h"



const query_engin_G2Constants g_query_engin_G2_constants;

query_engin_G2Constants::query_engin_G2Constants() {
}



